### ISSUE TITLE
confirm: /v2/{repo}/manifests not a valid API call

### ISSUE THREAD

**Issue by twaugh** [release-engineering/dockpulp#77]
Valid API calls include:

- /v2/{repo}/tags/list
- /v2/{repo}/manifests/{ref}

To find out the sha256 refs for manifests, you need to ask for the manifest by tag and note the Docker-Content-Digest header in the response.

**Comment by twaugh** [comment]
@breillyrh

**Comment by twaugh** [comment]
From Akamai, for instance, you'll get a 404 when asking for "/v2/{repo}/manifests/".

**Comment by breillyrh** [comment]
The only place where dock-pulp uses /v2/{repo}/manifests is here:
https://github.com/release-engineering/dockpulp/blob/master/bin/dock-pulp.py#L367

It checks that url specifically to make sure the repo is protected, and it *expects* a 404 (because it's used to check protected repos without sending the cert,key to confirm the repo is actually protected.
In this case it would cause false positives. I can use the /tags/list url instead perhaps to check protection is working (or remove the check entirely perhaps?) but it won't break dock-pulp.

The only other place where dock-pulp queries for manifests is here:
https://github.com/release-engineering/dockpulp/blob/master/bin/dock-pulp.py#L378

But as you can see, it is using /v2/{repo}/manifests/{ref}, not /v2/{repo}/manifests

**Comment by twaugh** [comment]
Ah, ok, got it.
